### ISSUE TITLE
[JOSS] add community guidelines

### ISSUE THREAD

**Issue by kandersolar** [qpv-research-group/rayflare#29]
One of the JOSS review items is:

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I don't think any of these three points are explicitly addressed (though maybe I missed it!).  Some packages include this sort of info in the GitHub README or as a page in their sphinx docs.  GitHub also has a feature for this that might be useful, see "Contributing" here: https://github.com/qpv-research-group/rayflare/community

xref https://github.com/openjournals/joss-reviews/issues/3460

**Comment by phoebe-p** [comment]
To-do list for my own use:
- [x] Code of conduct
- [x] Guide for contributing
- [x] Issue template
- [x] Support information

**Comment by phoebe-p** [comment]
@kanderso-nrel I think I have now covered all these things in PR #33, now merged into devel.

**Comment by kandersolar** [comment]
I agree, feel free to close!
